version: '3.8'

services:
  events_shatynska_green:
    image: shatynska/events-shatynska:latest
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=traefik-public'
      - 'traefik.http.routers.events_shatynska_green.entrypoints=https'
      - 'traefik.http.routers.events_shatynska_green.rule=Host(`events.shatynska.com`)'
      - 'traefik.http.routers.events_shatynska_green.tls=true'
      - 'traefik.http.routers.events_shatynska_green.tls.certresolver=letsEncrypt'
      - 'traefik.http.services.events_shatynska_green.loadbalancer.server.port=5173'
    ports:
      - 5020:5173
    networks:
      - traefik-public
      - events-shatynska

networks:
  traefik-public:
    external: true
  events-shatynska:
    external: true
