version: '3.8'

services:
  events_shatynska_blue:
    image: shatynska/events:latest
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=traefik-public'
      - 'traefik.http.routers.events_shatynska_blue.entrypoints=https'
      - 'traefik.http.routers.events_shatynska_blue.rule=Host(`test.events.shatynska.com`)'
      - 'traefik.http.routers.events_shatynska_blue.tls=true'
      - 'traefik.http.routers.events_shatynska_blue.tls.certresolver=letsEncrypt'
      - 'traefik.http.services.events_shatynska_blue.loadbalancer.server.port=5173'
    ports:
      - 5030:5173
    networks:
      - traefik-public
      - events-shatynska

networks:
  traefik-public:
    external: true
  events-shatynska:
    external: true
